name: Build & deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:        
          aws-access-key-id: ${{ EVERSE_AWS_S3_BUCKET_SECRET_KEY_ID }}
          aws-secret-access-key: ${{ EVERSE_AWS_S3_BUCKET_SECRET_KEY_SECRET }}
          aws-region: us-east-2
      - name: Deploy
        run: aws s3 sync ./public s3://everse-snack-forge.dashboard
